from .datamapper import MapperManager
from pandas import NaT, NA

DEFAULT_MAPPERS = {}

worksheet_mapper = MapperManager()

# Worksheet source column names

['Site_Name',
 'Site_Type',
 'CMIM_ID',
 'Site_Aliases',
 'Last_Revised',
 'NAD',
 'UTM_Zone',
 'Easting',
 'Northing',
 'Latitude',
 'Longitude',
 'Country',
 'Province_Territory',
 'NTS_Area',
 'Mining_District',
 'Parent',
 'Parent_ID',
 'Commodity1',
 'Commodity2',
 'Commodity3',
 'Commodity4',
 'Commodity5',
 'Commodity6',
 'Commodity7',
 'Commodity8',
 'Mine_Type',
 'Mining_Method',
 'Mine_Status',
 'Owner_Operator',
 'Past_Owners',
 'Dev_Stage',
 'DS_Comments',
 'Site_Access',
 'SA_Comments',
 'Shaft_Depth',
 'Construction_Year',
 'Year_Opened',
 'Year_Closed',
 'Reserves_Resources',
 'SEDAR',
 'Source_1',
 'Source_1_ID',
 'Source_1_Link',
 'Source_2',
 'Source_2_ID',
 'Source_2_Link',
 'Source_3',
 'Source_3_ID',
 'Source_3_Link',
 'Source_4',
 'Source_4_ID',
 'Source_4_Link',
 'Notes',
 'Orebody_Type',
 'Orebody_Class',
 'Ore_Minerals',
 'Processing_Method',
 'Ore_Processed',
 'Ore_Processed_Unit',
 'Other_Mineralization',
 'Spectral_Mineralization',
 'Forcing_Features',
 'Feature_References',
 'NOAMI_Status',
 'NOAMI_Site_Class',
 'Hazard_Class',
 'Hazard_System',
 'PRP_Rating',
 'Rehab_Plan',
 'EWS',
 'EWS_Rating',
 'Raise_Type',
 'History_Stability_Concerns',
 'Rating_Index',
 'Acid_Generating',
 'Treatment',
 'Current_Max_Height',
 'Tailings_Storage_Method',
 'Tailings_Volume',
 'Tailings_Capacity',
 'Tailings_Area',
 'Tailings_Area_From_Images',
 'Tailings_Area_Notes',
 'Au_Grade',
 'Au_Contained',
 'Au_Produced',
 'Ag_Grade',
 'Ag_Contained',
 'Ag_Produced',
 'Barite_Grade',
 'Barite_Contained',
 'Barite_Produced',
 'Bi_Grade',
 'Bi_Contained',
 'Bi_Produced',
 'Cd_Grade',
 'Cd_Contained',
 'Cd_Produced',
 'Coal_Type',
 'Coal_Rank',
 'Coal_Production',
 'Coal_Produced',
 'Co_Grade',
 'Co_Contained',
 'Co_Produced',
 'Cu_Grade',
 'Cu_Contained',
 'Cu_Produced',
 'Diamond',
 'Diamond_Grade',
 'Fe_Grade',
 'Fe_Produced',
 'Fe_Ore_Extracted',
 'Fe_Ore_Smelted',
 'Flourspar_Grade',
 'Flourspar_Contained',
 'Graphite_Grade',
 'Graphite_Contained',
 'Gypsum_Produced',
 'In_Grade',
 'In_Contained',
 'In_Produced',
 'Mo_Grade',
 'Mo_Contained',
 'Mo_Produced',
 'Ni_Grade',
 'Ni_Contained',
 'Ni_Produced',
 'Pb_Grade',
 'Pb_Contained',
 'Pb_Produced',
 'Pd_Grade',
 'Pd_Contained',
 'Pd_Produced',
 'Potash_Grade',
 'Potash_Contained',
 'Potash_Produced',
 'Pt_Grade',
 'Pt_Contained',
 'Pt_Produced',
 'Sb_Grade',
 'Sb_Contained',
 'Sb_Produced',
 'Sn_Grade',
 'Sn_Contained',
 'Sn_Produced',
 'U_Grade',
 'U_Contained',
 'U_Produced',
 'W_Grade',
 'W_Contained',
 'W_Produced',
 'Zn_Grade',
 'Zn_Contained',
 'Zn_Produced']

# Worksheet data types
cmti_dtypes = {'Site_Name':'U', 'Site_Type':'U', 'CMIM_ID':'U', 'Site_Aliases': 'U', 'Last_Revised': 'datetime64[ns]',
    'NAD': 'Int64', 'UTM_Zone':'Int64', 'Easting':'Int64', 'Northing':'Int64', 'Latitude': 'f',
    'Longitude': 'f', 'Country':'U','Province_Territory': 'U', 'NTS_Area':'U', 'Mining_District': 'U', 'Parent': 'U', 'Parent_ID': 'U',
    'Commodity1':'U', 'Commodity2':'U', 'Commodity3': 'U', 'Commodity4': 'U', 'Commodity5': 'U', 'Commodity6':'U',
    'Commodity7':'U', 'Commodity8':'U', 'Mine_Type':'U',  'Mining_Method':'U', 'Mine_Status': 'U',
    'Owner_Operator': 'U', 'Past_Owners': 'U', 'Dev_Stage': 'U', 'DS_Comments': 'U', 'Site_Access': 'U',
    'SA_Comments': 'U',  'Shaft_Depth':'f', 'Construction_Year': 'Int64', 'Year_Opened': 'Int64', 'Year_Closed': 'Int64',
    'Reserves_Resources': 'f', 'SEDAR': 'U', 'Source_1': 'U', 'Source_1_ID': 'U', 'Source_1_Link': 'U',
    'Source_2': 'U', 'Source_2_ID': 'U', 'Source_2_Link': 'U', 'Source_3': 'U', 'Source_3_ID': 'U', 'Source_3_Link': 'U',
    'Source_4': 'U', 'Source_4_ID': 'U', 'Source_4_Link': 'U', 'Notes': 'U', 'Orebody_Type':'U', 'Orebody_Class':'U',
    'Ore_Minerals':'U', 'Processing_Method':'U',  'Ore_Processed': 'f', 'Ore_Processed_Unit':'U',
    'Other_Mineralization': 'U', 'Spectral_Mineralization': 'U', 'Forcing_Features': 'U', 'Feature_References': 'U',
    'NOAMI_Status': 'U', 'NOAMI_Site_Class': 'U', 'Hazard_Class':'U', 'Hazard_System':'U', 'PRP_Rating':'U',
    'Rehab_Plan':'U', 'EWS':'U', 'EWS_Rating':'U', 'Raise_Type':'U', 'History_Stability_Concerns':'U',
    'Rating_Index':'U', 'Acid_Generating':'U',  'Treatment':'U', 'Current_Max_Height': 'f', 'Tailings_Storage_Method': 'U',
    'Tailings_Volume': 'f', 'Tailings_Capacity':'f', 'Tailings_Area':'f', 'Tailings_Area_From_Images':'f',
    'Tailings_Area_Notes': 'U', 'Orebody_Type':'U', 'Orebody_Class':'U', 'Orebody_Minerals':'U', 'Ore_Processed':'f'}
grades = ['Au_Grade', 'Au_Contained', 'Au_Produced', 'Ag_Grade', 'Ag_Contained', 'Ag_Produced', 'Barite_Grade',
    'Barite_Contained', 'Barite_Produced', 'Bi_Grade', 'Bi_Contained', 'Bi_Produced', 'Cd_Grade', 'Cd_Contained',
    'Cd_Produced', 'Coal_Type', 'Coal_Rank', 'Coal_Production', 'Coal_Produced', 'Co_Grade', 'Co_Contained',
    'Co_Produced', 'Cu_Grade', 'Cu_Contained', 'Cu_Produced', 'Diamond', 'Diamond_Grade', 'Fe_Grade', 'Fe_Produced',
    'Fe_Ore_Extracted', 'Fe_Ore_Smelted', 'Flourspar_Grade', 'Flourspar_Contained', 'Graphite_Grade', 'Graphite_Contained',
    'Gypsum_Produced', 'In_Grade', 'In_Contained', 'In_Produced', 'Mo_Grade', 'Mo_Contained', 'Mo_Produced',
    'Ni_Grade', 'Ni_Contained', 'Ni_Produced', 'Pb_Grade', 'Pb_Contained', 'Pb_Produced', 'Pd_Grade', 'Pd_Contained',
    'Pd_Produced', 'Potash_Grade', 'Potash_Contained', 'Potash_Produced', 'Pt_Grade', 'Pt_Contained', 'Pt_Produced',
    'Sb_Grade', 'Sb_Contained', 'Sb_Produced', 'Sn_Grade', 'Sn_Contained', 'Sn_Produced', 'U_Grade', 'U_Contained',
    'U_Produced', 'W_Grade', 'W_Contained', 'W_Produced', 'Zn_Grade', 'Zn_Contained', 'Zn_Produced']

for grade in grades:
    cmti_dtypes[grade] = 'f'
cmti_defaults = {}
for key, val in cmti_dtypes.items():
    if val == 'Site_Aliases':
        cmti_defaults[key] = None
    elif val[0] in ['i','I','u','f']:
        cmti_defaults[key] = None
    elif val == 'U':
        cmti_defaults[key] = 'Unknown'
    elif val == 'datetime64[ns]':
        cmti_defaults[key] = NaT

# OMI

omi_mapper = MapperManager()

omi_columns = {
    'MDI_IDENT',
    'NAME',
    'STATUS',
    'TWP_AREA',
    'RGP_DIST',
    'P_COMMOD',
    'S_COMMOD',
    'ALL_NAMES',
    'DEP_CLASS',
    'LONGITUDE',
    'LATITUDE',
    'LL_DATUM',
    'DETAIL'
 }

omi_dtypes = {
    'MDI_IDENT': 'U',
    'NAME': 'U',
    'STATUS': 'U',
    'TWP_AREA': 'U',
    'RGP_DIST': 'U',
    'P_COMMOD': 'U',
    'S_COMMOD': 'U',
    'ALL_NAMES': 'U',
    'DEP_CLASS': 'U',
    'LONGITUDE': 'f4',
    'LATITUDE': 'f4',
    'LL_DATUM': 'U',
    'DETAIL': 'U'
}

omi_defaults = ["Unknown" if t == "U" else NA for t in omi_dtypes]