[sources]
worksheet = data\sources\CMTI_Worksheet.xlsx
oam = data\sources\OAM_2024_EN.xlsx
omi = data\sources\OMI_filtered.xlsx
bcahm = data\sources\BCAHM_2024-05-14-filtered.xlsx
nsmtd = data\sources\NSMTD.csv

[supplemental]
critical_minerals = data\supplemental\cmList.csv
metals = data\supplemental\metals.csv
elements = data\supplemental\elements.csv
oam_comm_names = data\supplemental\OAM_commodity_names.csv