[sources]
critical_minerals = cmti_tools\data\cmList.csv
metals = cmti_tools\data\metalList_utf.csv
elements = cmti_tools\data\elements.csv

[engine]
engine = postgresql+psycopg2://postgres:postgres@localhost:5432/cmti