[sources]
worksheet = data\sources\worksheet
oam = data\sources\oam
omi = data\sources\omi
bcahm = data\sources\bcahm
nsmtd = data\sources\nsmtd

[supplemental]
critical_minerals = data\supplemental\cmList.csv
metals = data\supplemental\metals.csv
elements = data\supplemental\elements.csv
oam_comm_names = data\supplemental\OAM_commodity_names.csv