# Dict to convert the CMDB worksheet column names to the database table column names
worksheet_table_mapping = {
    "cmdb_id": "CMIM_ID",
    "name": "Site_Name",
    "prov_terr": "Province_Territory",
    "last_revised": "Last_Revised",
    "nad": "NAD",
    "utm_zone": "UTM_Zone",
    "easting": "Easting",
    "northing": "Northing",
    "latitude": "Latitude",
    "longitude": "Longitude",
    "nts_area": "NTS_Area",
    "mining_district": "Mining_District",
    "mine_type": "Mine_Type",
    "mine_status": "Mine_Status",
    "mining_method": "Mining_Method",
    "development_stage": "Dev_Stage",
    "site_access": "Site_Access",
    "construction_year": "Construction_Year",
    "orebody_type": "Orebody_Type",
    "orebody_class": "Orebody_Class",
    "orebody_minerals": "Ore_Minerals",
    "ore_processed": "Ore_Processed",
    "ore_processed_unit": "Ore_Processed_Unit",
    # Likely to be removed:
    "ds_comments": "DS_Comments",
    "sa_comments": "SA_Comments",
    "shaft_depth": "Shaft_Depth",
    "reserves_resources": "Reserves_Resources",
    "sedar": "SEDAR",
    "notes": "Notes",
    "other_mineralization": "Other_Mineralization",
    "forcing_features": "Forcing_Features",
    "feature_references": "Feature_References",
    "noami_status": "NOAMI_Status",
    "noami_site_class": "NOAMI_Site_Class",
    "hazard_class": "Hazard_Class",
    "hazard_system": "Hazard_System",
    "prp_rating": "PRP_Rating",
    "rehab_plan": "Rehab Plan",
    "ews": "EWS",
    "ews_rating": "EWS_Rating"
}

# The following map inputs to the worksheet column

omi_mapping = {
    'MDI_IDENT': 'Source_1_ID',
    'NAME': 'Site_Name',
    'STATUS:': 'Mine_Status',
    'P_COMMOD': 'Commodity1',
    'S_COMMOD': 'Commodity2',
    'ALL_NAMES': 'Site_Aliases',
    'DEP_CLASS': 'Orebody_Class',
    'LONGITUDE': 'Longitude',
    'LATITUDE': 'Latitude',
    'LL_DATUM': 'NAD',
    'DETAIL': 'Source_1_Link'
}

oam_mapping = {
    'OID': 'Source_1_ID',
    'Lat_DD': 'Latitude',
    'Long_DD': 'Longitude',
    'Jurisdiction': 'Province_Territory',
    'Name': 'Site_Name',
    'Status': 'Mine_Status',
    'Commodity_Code': 'Commodity1',
    'Mined_Quantity': 'Ore_Processed',
    'Mine_Type': 'Mine_Type',
    'Last_Year': 'Year_Closed',
    'URL': 'Source_1_Link',
    'Forcing_Features': 'Forcing_Features',
    'Feature_Class': 'NOAMI_Site_Class',
    'Landowner': 'Owner_Operator',
    'Last_Operator': 'Past_Owners',
    'Start_Date': 'Year_Opened',
    'Last_Updated': 'Last_Revised',
}

bcahm_mapping = {
    "OBJECTID": "Source_1_ID",
    "MINFILNO": "Source_2_ID",
    "NAME1": "Site_Name",
    "NAME2": "Site_Aliases",
    "STATUS": "Mine_Status",
    "LATITUDE": "Latitude",
    "LONGITUDE": "Longitude",
    "UTM_ZONE": "UTM_Zone",
    "UTM_NORT": "Northing",
    "UTM_EAST": "Easting",
    "COMMOD_C1": "Commodity1",
    "COMMOD_C2": "Commodity2",
    "COMMOD_C3": "Commodity3",
    "DEPOSITTYPE_D1": "Orebody_Type",
    # "DEPOSITTYPE_D2": "U",
    "DEPOSITCLASS_D1": "Orebody_Class",
    # "DEPOSITCLASS_D2": "U",
    "NTSMAP_C1": "NTS_Area",
    # "NTSMAP_C2": "U",
    "Mine_Name": "Site_Name",
    "Mine_Statu": "Mine_Status", # 'Statu' is a typo in the source
    "Disposal_Method": "Tailings_Storage_Method",
    "Milled": "Ore_Processed",
    "Mine_type": "Mine_Type",
    "Permitee1": "Owner_Operator",
    "Permittee2": "Owner_Operator",
    "URL": "Source_1_Link",
    "First_Year": "Year_Opened",
    "Last_Year": "Year_Closed",
}

nsmtd_mapping = {
    'OBJECTID': 'Source_1_ID',
    'Name': 'Site_Name',
    'Latitude': 'Latitude',
    'Longitude': 'Longitude',
    'Tonnes': 'Ore_Processed',
    'Commodity': 'Commodity1',
    'Dates': 'Start_Date',
    'InfoSource': 'Source_2',
    # 'AreaHa': 'Tailings_Area',
    'Shape_Area': 'Tailings_Area',
}